discourse_posthog:
  enable_discourse_posthog_plugin:
    default: false
  posthog_api_host:
    default: "https://eu.i.posthog.com"
    type: string
  posthog_ui_host:
    default: "https://eu.posthog.com"
    type: string
  posthog_api_key:
    default: ""
    type: string
  posthog_identify_user_by:
    client: true
    default: "Email (hashed)"
    type: enum
    choices:
      - "No User Identification"
      - "Email"
      - "Email (hashed)"

#######################################
########## Posthog Features ###########
#######################################
  posthog_feature_disable_surveys:
    default: true
  posthog_feature_disable_session_recording:
    default: true
  posthog_cookie_expiration_in_days:
    default: 90
  posthog_api_version:
    default: "2025-11-30"
    type: string